### ISSUE TITLE
Looking for ways to contact you

### ISSUE THREAD

**Issue by seanoh1989** [optc/optc.github.io#2]
Hello, I'm sorry that I'm issuing an issue here without actual issue. I am looking for any ways to contact you direct to talk about possible native app development opportunity. I already started making an Android app for OPTC with someone else and I wanted to ask if you want to join. The data you have will be a huge help to the team to save time. Please let me know what you think.

seanoh1989@gmail.com

and again I'm sorry that I'm doing this.

Thanks,
Sean

**Comment by optc** [comment]
Thanks for the offer, but I'm not really interested in branching out with the site, it's just a hobby I'm doing in my free time. Feel free to use the data however you want though, it's not obfuscated and most of it (except maybe for the growth parameters and the translations of the captain abilities/specials) is stuff you can easily find on either the official guide or other Japanese sites, so it's not like it's any secret.
